name: 'tests'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v2.3.4'
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.4.0'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: Lint Files
        run: 'npm run lint'

      - name: 'Run Tests and Coverage'
        env:
          CI: true
        run: 'npm run coverage'

      - name: 'Coveralls Parallel'
        uses: 'coverallsapp/github-action@master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: './coverage/lcov.info'

      - name: 'Coveralls Finished'
        uses: 'coverallsapp/github-action@master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
